name: referencelibrary
description: "Reference Library mobile app."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.0.1
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  dio: ^5.9.0
  connectivity_plus: ^7.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  crypto: ^3.0.7
  webview_flutter: ^4.13.1
  flutter_cache_manager: ^3.4.1
  xml: ^6.6.1
  url_launcher: ^6.3.0
  archive: ^4.0.3
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^4.0.0+1

flutter:
  uses-material-design: true
